#!/usr/bin/env python3
"""Extract summary statistics from a gitstats JSON report and print a
Markdown snippet suitable for posting as a GitHub PR comment.

Usage:
  python pr-summary.py <report.json> [--repo-url https://github.com/owner/repo]
"""

import json
import sys
from pathlib import Path


def format_size(bytes_val: int) -> str:
    """Format bytes into a human-readable string."""
    if bytes_val < 1024:
        return f"{bytes_val} B"
    elif bytes_val < 1024 * 1024:
        return f"{bytes_val / 1024:.1f} KB"
    else:
        return f"{bytes_val / (1024 * 1024):.1f} MB"


def format_number(n: int) -> str:
    """Format an integer with thousand separators."""
    return f"{n:,}"


def generate_summary(json_path: str, repo_url: str = "") -> str:
    """Generate a Markdown summary from gitstats JSON output."""
    data = json.loads(Path(json_path).read_text())

    total_commits = data.get("total_commits", 0)
    total_files = data.get("total_files", 0)
    total_lines = data.get("total_lines", 0)
    total_authors = data.get("total_authors", 0)
    total_size = data.get("total_size", 0)
    longest_streak = data.get("longest_streak", 0)

    # Dates
    first_ts = data.get("first_commit_stamp", 0)
    last_ts = data.get("last_commit_stamp", 0)

    lines = ["## 📊 GitStats Report"]
    if repo_url:
        lines.append(f"**Repository:** <{repo_url}>")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("| ------ | ----- |")
    lines.append(f"| Total Commits | {format_number(total_commits)} |")
    lines.append(f"| Total Files | {format_number(total_files)} |")
    lines.append(f"| Lines of Code | {format_number(total_lines)} |")
    lines.append(f"| Authors | {format_number(total_authors)} |")
    lines.append(f"| Repository Size | {format_size(total_size)} |")
    lines.append(f"| Longest Streak | {longest_streak} days |")

    if total_commits > 0:
        authors_data = data.get("authors", {})
        sorted_authors = sorted(
            authors_data.items(),
            key=lambda x: x[1].get("commits", 0),
            reverse=True,
        )[:10]
        if sorted_authors:
            lines.append("")
            lines.append("### 🔝 Top Contributors")
            lines.append("| Author | Commits | Lines Added | Lines Removed |")
            lines.append("| ------ | ------- | ----------- | ------------- |")
            for name, stats in sorted_authors:
                commits = format_number(stats.get("commits", 0))
                added = format_number(stats.get("lines_added", 0))
                removed = format_number(stats.get("lines_removed", 0))
                lines.append(f"| {name} | {commits} | {added} | {removed} |")

    lines.append("")
    lines.append(
        ":information_source: **How to view:** Download the artifact from the "
        "workflow run, extract the zip, and open `index.html` in your browser. "
        "Or run `python -m http.server 8000 -d <report-dir>` locally."
    )
    lines.append("")
    lines.append(
        "<sub>Generated by [GitStats]"
        "(https://github.com/shenxianpeng/gitstats) · "
        "[Documentation](https://gitstats.readthedocs.io/)</sub>"
    )

    return "\n".join(lines)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python pr-summary.py <report.json> [--repo-url URL]")
        sys.exit(1)

    json_path = sys.argv[1]
    repo_url = ""
    if len(sys.argv) >= 4 and sys.argv[2] == "--repo-url":
        repo_url = sys.argv[3]

    print(generate_summary(json_path, repo_url))
