# Copyright (c) 2007-2014 Heikki Hokkanen <hoxu@users.sf.net> & others contributors
# GPLv2 / GPLv3
# Copyright (c) 2024-present Xianpeng Shen <xianpeng.shen@gmail.com>.
# GPLv2 / GPLv3
import datetime
import html
import json
import math
import os
import shutil
import time
from typing import Any

from gitstats import WEEKDAYS, get_i18n_text, load_config
from gitstats.utils import (
    get_git_version,
    get_pipe_output,
    get_version,
)

_FLEX_CONTAINER = '<div style="display:flex;gap:24px;align-items:flex-start">'
_FLEX_CHILD = '<div style="flex:1;min-width:0">'
_FLEX_CLOSE = "</div></div>"


class ReportCreator:
    """Creates the actual report based on given data."""

    def __init__(self):
        self.data = None
        self.path = None

    def create(self, data, path):
        self.data = data
        self.path = path


class HTMLReportCreator(ReportCreator):
    @staticmethod
    def _heat_level(value, max_value):
        if max_value <= 0 or value <= 0:
            return 0
        ratio = float(value) / float(max_value)
        if ratio <= 0.25:
            return 1
        if ratio <= 0.50:
            return 2
        if ratio <= 0.75:
            return 3
        return 4

    @classmethod
    def _heat_td_class(cls, value, max_value):
        return f"heat heat{cls._heat_level(value, max_value)}"

    def create(self, data: Any, path: str) -> None:
        ReportCreator.create(self, data, path)
        self.title = data.project_name

        # copy static files to the report directory
        basedir = os.path.dirname(os.path.abspath(__file__))
        for file in (
            load_config()["style"],
            "sortable.js",
            "chart.umd.min.js",
            "arrow-up.gif",
            "arrow-down.gif",
            "arrow-none.gif",
        ):
            src = basedir + "/" + file
            if os.path.exists(src):
                shutil.copyfile(src, path + "/" + file)

        self.create_index_html(data, path)
        self.create_activity_html(data, path)
        self.create_authors_html(data, path)
        self.create_files_html(data, path)
        self.create_lines_html(data, path)
        self.create_tags_html(data, path)
        self.create_ownership_html(data, path)
        self.create_history_html(data, path)

        # Create AI Insights page if AI is enabled
        if hasattr(data, "ai_summaries") and data.ai_summaries:
            self.create_ai_insights_html(data, path)

    def create_index_html(self, data: Any, path: str) -> None:
        f = open(path + "/index.html", "w", encoding="utf-8")
        format = "%Y-%m-%d %H:%M:%S"
        self.print_header(f)

        self.print_nav(f)

        f.write("<h1>General</h1>")

        f.write(html_header(2, "Git Overview"))

        f.write("<table border='1' cellspacing='0' cellpadding='4'>")
        f.write(f"<tr><td>Project Name</td><td>{data.project_name}</td></tr>")
        f.write(
            "<tr><td>Generated On</td><td>%s (in %d seconds)</td></tr>"
            % (
                datetime.datetime.now().strftime(format),
                time.time() - data.get_stamp_created(),
            )
        )
        f.write(
            f"<tr><td>Generated By</td><td>gitstats {get_version()}, {get_git_version()}</td></tr>"
        )
        f.write(
            f"<tr><td>Report Period</td><td>{data.get_first_commit_date().strftime(format)} to {data.get_last_commit_date().strftime(format)}</td></tr>"
        )
        f.write(
            "<tr><td>Project Age</td><td>%d days, %d active days (%3.2f%%)</td></tr>"
            % (
                data.get_commit_delta_days(),
                len(data.get_active_days()),
                (100.0 * len(data.get_active_days()) / data.get_commit_delta_days()),
            )
        )
        f.write(
            f"<tr><td>Longest Streak</td><td>{data.get_longest_streak()} consecutive active days</td></tr>"
        )
        f.write(f"<tr><td>Total Files</td><td>{data.get_total_files()}</td></tr>")
        f.write(
            "<tr><td>Total Lines of Code</td><td>%s (%d added, %d removed)</td></tr>"
            % (data.get_total_loc(), data.total_lines_added, data.total_lines_removed)
        )
        f.write(
            f"<tr><td>Total Commits</td><td>{data.get_total_commits()} (average {float(data.get_total_commits()) / len(data.get_active_days()):.1f} commits per active day, {float(data.get_total_commits()) / data.get_commit_delta_days():.1f} per all days)</td></tr>"
        )
        f.write(
            f"<tr><td>Authors</td><td>{data.get_total_authors()} (average {(1.0 * data.get_total_commits()) / data.get_total_authors():.1f} commits per author)</td></tr>"
        )
        f.write("</table>")

        self.print_footer(f)
        f.write("</body>\n</html>")
        f.close()

    def create_activity_html(self, data, path):
        ###
        # Activity
        f = open(path + "/activity.html", "w", encoding="utf-8")
        self.print_header(f)
        self.print_nav(f)
        f.write("<h1>Activity</h1>")

        # Streak summary
        self._write_streak_summary(f, data)

        self._write_yearly_activity_section(f, data)
        self._write_weekly_activity_section(f, data)
        self._write_hour_of_day_section(f, data)
        self._write_day_of_week_section(f, data)
        self._write_hour_of_week_section(f, data)
        self._write_month_of_year_section(f, data)
        self._write_commits_by_year_month_section(f, data)
        self._write_commits_by_year_section(f, data)
        self._write_commits_by_timezone_section(f, data)

        self.print_footer(f)
        f.write("</body></html>")
        f.close()

    def _write_streak_summary(self, f, data) -> None:
        """Write streak summary paragraph."""
        longest_streak = data.get_longest_streak()
        if longest_streak > 0:
            f.write(
                "<p><strong>Longest Streak:</strong> %d consecutive active days. "
                "A long streak indicates sustained development momentum.</p>" % longest_streak
            )

    def _write_yearly_activity_section(self, f, data) -> None:
        """Write yearly activity section with chart."""
        log_output = get_pipe_output(["git log --reverse --pretty=format:%ct"], quiet=True)
        first_commit_timestamp = log_output.split("\n")[0] if log_output else ""
        if first_commit_timestamp:
            repo_age_years = (time.time() - int(first_commit_timestamp)) / 31536000
            years_count = max(5, int(math.ceil(repo_age_years / 5.0)) * 5)
        else:
            years_count = 5
        f.write(html_header(2, "Yearly activity"))
        f.write("<p>Last %d years</p>" % years_count)

        now = datetime.datetime.now()
        deltayear = datetime.timedelta(365)
        years: list[str] = []
        stampcur = now
        for _ in range(years_count):
            years.insert(0, stampcur.strftime("%Y"))
            stampcur -= deltayear

        yearly_values = [data.commits_by_year.get(int(y), 0) for y in years]
        f.write(
            self._render_chartjs(
                "chart-yearly-activity",
                "bar",
                years,
                [{"label": "Commits", "data": yearly_values}],
                y_label="Commits",
                aspect_ratio=4,
            )
        )

    def _write_weekly_activity_section(self, f, data) -> None:
        """Write weekly activity section with chart."""
        weeks_count = 32
        f.write(html_header(2, "Weekly activity"))
        f.write("<p>Last %d weeks</p>" % weeks_count)

        now = datetime.datetime.now()
        deltaweek = datetime.timedelta(7)
        weeks: list[str] = []
        stampcur = now
        for _ in range(weeks_count):
            weeks.insert(0, stampcur.strftime("%Y-%W"))
            stampcur -= deltaweek

        weekly_values = [data.activity_by_year_week.get(w, 0) for w in weeks]
        f.write(
            self._render_chartjs(
                "chart-weekly-activity",
                "bar",
                weeks,
                [{"label": "Commits", "data": weekly_values}],
                y_label="Commits",
                x_ticks_rotate=True,
                aspect_ratio=5,
            )
        )

    def _write_hour_of_day_section(self, f, data) -> None:
        """Write hour of day section with table and chart."""
        f.write(html_header(2, "Hour of Day"))
        totalcommits = data.get_total_commits()
        hour_of_day = data.get_activity_by_hour_of_day()
        busiest = data.activity_by_hour_of_day_busiest

        f.write("<table><tr><th>Hour</th>")
        for i in range(24):
            f.write("<th>%d</th>" % i)
        f.write("</tr>\n<tr><th>Commits</th>")
        for i in range(24):
            if i in hour_of_day:
                f.write(
                    '<td class="%s">%d</td>'
                    % (self._heat_td_class(hour_of_day[i], busiest), hour_of_day[i])
                )
            else:
                f.write(f'<td class="{self._heat_td_class(0, 0)}">0</td>')
        f.write("</tr>\n<tr><th>%</th>")
        for i in range(24):
            if i in hour_of_day:
                f.write(
                    f'<td class="{self._heat_td_class(hour_of_day[i], busiest)}">'
                    f"{(100.0 * hour_of_day[i]) / totalcommits:.2f}</td>"
                )
            else:
                f.write(f'<td class="{self._heat_td_class(0, 0)}">0.00</td>')
        f.write("</tr></table>")

        h_labels = list(range(24))
        h_values = [hour_of_day.get(h, 0) for h in h_labels]
        f.write(
            self._render_chartjs(
                "chart-hour-of-day",
                "bar",
                h_labels,
                [{"label": "Commits", "data": h_values}],
                y_label="Commits",
            )
        )

    def _write_day_of_week_section(self, f, data) -> None:
        """Write day of week section with table and chart."""
        f.write(html_header(2, "Day of Week"))
        day_of_week = data.get_activity_by_day_of_week()
        totalcommits = data.get_total_commits()

        f.write(_FLEX_CONTAINER)
        f.write("<table><tr><th>Day</th><th>Total (%)</th></tr>")
        for d in range(7):
            f.write("<tr>")
            f.write(f"<th>{WEEKDAYS[d]}</th>")
            if d in day_of_week:
                f.write(
                    "<td>%d (%.2f%%)</td>"
                    % (day_of_week[d], (100.0 * day_of_week[d]) / totalcommits)
                )
            else:
                f.write("<td>0</td>")
            f.write("</tr>")
        f.write("</table>")
        dow_labels = list(WEEKDAYS)
        dow_values = [day_of_week.get(d, 0) for d in range(7)]
        f.write(_FLEX_CHILD)
        f.write(
            self._render_chartjs(
                "chart-day-of-week",
                "bar",
                dow_labels,
                [{"label": "Commits", "data": dow_values}],
                y_label="Commits",
                max_bar_thickness=40,
                aspect_ratio=4,
            )
        )
        f.write(_FLEX_CLOSE)

    def _write_hour_of_week_section(self, f, data) -> None:
        """Write hour of week section as a heat table."""
        f.write(html_header(2, "Hour of Week"))
        f.write("<table>")
        f.write("<tr><th>Weekday</th>")
        for hour in range(24):
            f.write("<th>%d</th>" % hour)
        f.write("</tr>")
        for weekday in range(7):
            f.write(f"<tr><th>{WEEKDAYS[weekday]}</th>")
            for hour in range(24):
                commits = data.activity_by_hour_of_week.get(weekday, {}).get(hour, 0)
                f.write(
                    '<td class="{}">{}</td>'.format(
                        self._heat_td_class(commits, data.activity_by_hour_of_week_busiest),
                        ("%d" % commits) if commits else "",
                    )
                )
            f.write("</tr>")
        f.write("</table>")

    def _write_month_of_year_section(self, f, data) -> None:
        """Write month of year section with table and chart."""
        f.write(html_header(2, "Month of Year"))
        f.write(_FLEX_CONTAINER)
        f.write("<table><tr><th>Month</th><th>Commits (%)</th></tr>")
        total = data.get_total_commits()
        for mm in range(1, 13):
            commits = data.activity_by_month_of_year.get(mm, 0)
            f.write(
                "<tr><td>%d</td><td>%d (%.2f %%)</td></tr>"
                % (mm, commits, (100.0 * commits) / total)
            )
        f.write("</table>")
        moy_labels = list(range(1, 13))
        moy_values = [data.activity_by_month_of_year.get(mm, 0) for mm in moy_labels]
        f.write(_FLEX_CHILD)
        f.write(
            self._render_chartjs(
                "chart-month-of-year",
                "bar",
                moy_labels,
                [{"label": "Commits", "data": moy_values}],
                y_label="Commits",
                max_bar_thickness=40,
                aspect_ratio=4,
            )
        )
        f.write(_FLEX_CLOSE)

    def _write_commits_by_year_month_section(self, f, data) -> None:
        """Write commits by year/month section with table and chart."""
        f.write(html_header(2, "Commits by year/month"))
        f.write(_FLEX_CONTAINER)
        f.write(
            "<table><tr><th>Month</th><th>Commits</th><th>Lines added</th><th>Lines removed</th></tr>"
        )
        for yymm in sorted(data.commits_by_month.keys(), reverse=True):
            f.write(
                "<tr><td>%s</td><td>%d</td><td>%d</td><td>%d</td></tr>"
                % (
                    yymm,
                    data.commits_by_month.get(yymm, 0),
                    data.lines_added_by_month.get(yymm, 0),
                    data.lines_removed_by_month.get(yymm, 0),
                )
            )
        f.write("</table>")
        cbym_keys = sorted(data.commits_by_month.keys())
        cbym_values = [data.commits_by_month[k] for k in cbym_keys]
        f.write(_FLEX_CHILD)
        f.write(
            self._render_chartjs(
                "chart-commits-by-year-month",
                "bar",
                cbym_keys,
                [{"label": "Commits", "data": cbym_values}],
                y_label="Commits",
                x_ticks_rotate=True,
            )
        )
        f.write(_FLEX_CLOSE)

    def _write_commits_by_year_section(self, f, data) -> None:
        """Write commits by year section with table and chart."""
        f.write(html_header(2, "Commits by Year"))
        f.write(_FLEX_CONTAINER)
        f.write(
            "<table><tr><th>Year</th><th>Commits (% of all)</th><th>Lines added</th><th>Lines removed</th></tr>"
        )
        total = data.get_total_commits()
        for yy in sorted(data.commits_by_year.keys(), reverse=True):
            f.write(
                "<tr><td>%s</td><td>%d (%.2f%%)</td><td>%d</td><td>%d</td></tr>"
                % (
                    yy,
                    data.commits_by_year.get(yy, 0),
                    (100.0 * data.commits_by_year.get(yy, 0)) / total,
                    data.lines_added_by_year.get(yy, 0),
                    data.lines_removed_by_year.get(yy, 0),
                )
            )
        f.write("</table>")
        if data.commits_by_year:
            cby_all_years = list(
                range(
                    min(data.commits_by_year.keys()),
                    max(data.commits_by_year.keys()) + 1,
                )
            )
        else:
            cby_all_years = []
        cby_values = [data.commits_by_year.get(y, 0) for y in cby_all_years]
        f.write(_FLEX_CHILD)
        f.write(
            self._render_chartjs(
                "chart-commits-by-year",
                "bar",
                cby_all_years,
                [{"label": "Commits", "data": cby_values}],
                y_label="Commits",
            )
        )
        f.write(_FLEX_CLOSE)

    def _write_commits_by_timezone_section(self, f, data) -> None:
        """Write commits by timezone section as a heat table."""
        f.write(html_header(2, "Commits by Timezone"))
        max_commits_on_tz = max(data.commits_by_timezone.values())
        tz_sorted = sorted(data.commits_by_timezone, key=lambda n: int(n))
        f.write('<table class="heat"><tr>')
        for i in tz_sorted:
            f.write(f"<th>{i}</th>")
        f.write("</tr>\n<tr>")
        for i in tz_sorted:
            commits = data.commits_by_timezone[i]
            f.write(
                '<td class="heat %s">%d</td>'
                % (self._heat_td_class(commits, max_commits_on_tz), commits)
            )
        f.write("</tr></table>")

    def _build_author_time_series(self, data):
        """Build per-author cumulative lines and commits time series for Chart.js.

        For large repositories, data points are automatically downsampled to keep
        the HTML file size manageable and Chart.js rendering fast. Since the stored
        values are already cumulative, downsampling preserves the chart shape.
        """
        authors_to_plot = data.get_authors(load_config()["max_authors"])
        sorted_stamps = sorted(data.changes_by_date_by_author.keys())
        total_points = len(sorted_stamps)

        # Target max ~500 data points per chart to prevent browser lag and huge HTML.
        # 500 points covers ~10 years at weekly granularity — more than enough for
        # cumulative line charts.
        MAX_POINTS = 500
        if total_points > MAX_POINTS:
            step = total_points / MAX_POINTS
            sampled_indices = {int(i * step) for i in range(MAX_POINTS)}
            sampled_indices.add(total_points - 1)  # ensure the last point is always included
        else:
            sampled_indices = set(range(total_points))

        lines_by_authors = dict.fromkeys(authors_to_plot, 0)
        commits_by_authors = dict.fromkeys(authors_to_plot, 0)
        time_labels = []
        per_author_lines = {a: [] for a in authors_to_plot}
        per_author_commits = {a: [] for a in authors_to_plot}

        for i, stamp in enumerate(sorted_stamps):
            # Update running totals: only the author(s) of this commit changed
            for author in data.changes_by_date_by_author[stamp]:
                if author in authors_to_plot:
                    lines_by_authors[author] = data.changes_by_date_by_author[stamp][author][
                        "lines_added"
                    ]
                    commits_by_authors[author] = data.changes_by_date_by_author[stamp][author][
                        "commits"
                    ]

            # Only record a data point if this index is in the sampled set
            if i in sampled_indices:
                time_labels.append(datetime.datetime.fromtimestamp(stamp).strftime("%Y-%m-%d"))
                for author in authors_to_plot:
                    per_author_lines[author].append(lines_by_authors[author])
                    per_author_commits[author].append(commits_by_authors[author])

        loc_datasets = [{"label": a, "data": per_author_lines[a]} for a in authors_to_plot]
        cba_datasets = [{"label": a, "data": per_author_commits[a]} for a in authors_to_plot]
        return time_labels, loc_datasets, cba_datasets

    def create_authors_html(self, data: Any, path: str) -> None:
        ###
        # Authors
        f = open(path + "/authors.html", "w", encoding="utf-8")
        self.print_header(f)

        self.print_nav(f)
        f.write("<h1>Authors</h1>")

        # Authors :: List of authors
        f.write(html_header(2, "List of Authors"))

        f.write('<table class="authors sortable" id="authors">')
        f.write(
            '<tr><th>Author</th><th>Commits (%)</th><th>+ lines</th><th>- lines</th><th>First commit</th><th>Last commit</th><th class="unsortable">Age</th><th>Active days</th><th># by commits</th></tr>'
        )
        for author in data.get_authors(load_config()["max_authors"]):
            info = data.get_author_info(author)
            f.write(
                "<tr><td>%s</td><td>%d (%.2f%%)</td><td>%d</td><td>%d</td><td>%s</td><td>%s</td><td>%s</td><td>%d</td><td>%d</td></tr>"
                % (
                    author,
                    info["commits"],
                    info["commits_frac"],
                    info["lines_added"],
                    info["lines_removed"],
                    info["date_first"],
                    info["date_last"],
                    info["timedelta"],
                    len(info["active_days"]),
                    info["place_by_commits"],
                )
            )
        f.write("</table>")

        allauthors = data.get_authors()
        if len(allauthors) > load_config()["max_authors"]:
            rest = allauthors[load_config()["max_authors"] :]
            max_list = load_config()["max_authors_list"]
            if len(rest) > max_list:
                shown = ", ".join(rest[:max_list])
                more = len(rest) - max_list
                f.write(
                    f'<p class="moreauthors">These didn\'t make it to the top:'
                    f" {shown}<em>, and {more} more authors</em></p>"
                )
            else:
                f.write(
                    '<p class="moreauthors">These didn\'t make it to the top: {}</p>'.format(
                        ", ".join(rest)
                    )
                )

        # Build per-author time series data for Chart.js
        time_labels, loc_datasets, cba_datasets = self._build_author_time_series(data)

        f.write(html_header(2, "Cumulated Added Lines of Code per Author"))
        f.write(
            self._render_chartjs(
                "chart-loc-by-author",
                "line",
                time_labels,
                loc_datasets,
                y_label="Lines",
                x_ticks_rotate=True,
            )
        )
        if len(allauthors) > load_config()["max_authors"]:
            f.write(
                '<p class="moreauthors">Only top %d authors shown</p>'
                % load_config()["max_authors"]
            )

        f.write(html_header(2, "Commits per Author"))
        f.write(
            self._render_chartjs(
                "chart-commits-by-author",
                "line",
                time_labels,
                cba_datasets,
                y_label="Commits",
                x_ticks_rotate=True,
            )
        )
        if len(allauthors) > load_config()["max_authors"]:
            f.write(
                '<p class="moreauthors">Only top %d authors shown</p>'
                % load_config()["max_authors"]
            )

        # Authors :: Author of Month
        f.write(html_header(2, "Author of Month"))
        f.write('<table class="sortable" id="aom">')
        f.write(
            '<tr><th>Month</th><th>Author</th><th>Commits (%%)</th><th class="unsortable">Next top %d</th><th>Number of authors</th></tr>'
            % load_config()["authors_top"]
        )
        for yymm in sorted(data.author_of_month.keys(), reverse=True):
            author_dict = data.author_of_month[yymm]
            authors = get_keys_sorted_by_values(author_dict)
            authors.reverse()
            commits = data.author_of_month[yymm][authors[0]]
            authors_str = ", ".join(authors[1 : load_config()["authors_top"] + 1])
            f.write(
                "<tr><td>%s</td><td>%s</td><td>%d (%.2f%% of %d)</td><td>%s</td><td>%d</td></tr>"
                % (
                    yymm,
                    authors[0],
                    commits,
                    (100.0 * commits) / data.commits_by_month[yymm],
                    data.commits_by_month[yymm],
                    authors_str,
                    len(authors),
                )
            )

        f.write("</table>")

        f.write(html_header(2, "Author of Year"))
        f.write(
            '<table class="sortable" id="aoy"><tr><th>Year</th><th>Author</th><th>Commits (%%)</th><th class="unsortable">Next top %d</th><th>Number of authors</th></tr>'
            % load_config()["authors_top"]
        )
        for yy in sorted(data.author_of_year.keys(), reverse=True):
            author_dict = data.author_of_year[yy]
            authors = get_keys_sorted_by_values(author_dict)
            authors.reverse()
            commits = data.author_of_year[yy][authors[0]]
            authors_str = ", ".join(authors[1 : load_config()["authors_top"] + 1])
            f.write(
                "<tr><td>%s</td><td>%s</td><td>%d (%.2f%% of %d)</td><td>%s</td><td>%d</td></tr>"
                % (
                    yy,
                    authors[0],
                    commits,
                    (100.0 * commits) / data.commits_by_year[yy],
                    data.commits_by_year[yy],
                    authors_str,
                    len(authors),
                )
            )
        f.write("</table>")

        # Domains
        f.write(html_header(2, "Commits by Domains"))
        domains_by_commits = get_keys_sorted_by_value_key(data.domains, "commits")
        domains_by_commits.reverse()  # most first
        f.write(_FLEX_CONTAINER)
        f.write("<table>")
        f.write("<tr><th>Domains</th><th>Total (%)</th></tr>")
        dom_labels = []
        dom_values = []
        n = 0
        for domain in domains_by_commits:
            if n == load_config()["max_domains"]:
                break
            n += 1
            info = data.get_domain_info(domain)
            dom_labels.append(domain)
            dom_values.append(info["commits"])
            f.write(
                "<tr><th>%s</th><td>%d (%.2f%%)</td></tr>"
                % (
                    domain,
                    info["commits"],
                    (100.0 * info["commits"] / data.get_total_commits()),
                )
            )
        f.write("</table>")
        f.write(_FLEX_CHILD)
        f.write(
            self._render_chartjs(
                "chart-domains",
                "bar",
                dom_labels,
                [{"label": "Commits", "data": dom_values}],
                y_label="Commits",
                x_ticks_rotate=True,
            )
        )
        f.write(_FLEX_CLOSE)

        # Contributor Growth Over Time
        if data.new_contributors_by_month:
            f.write(html_header(2, "Contributor Growth"))
            f.write(
                "<p><em>Number of first-time contributors per month. "
                "A growing trend indicates a healthy, welcoming project.</em></p>"
            )
            nc_keys = sorted(data.new_contributors_by_month.keys())
            nc_values = [data.new_contributors_by_month[k] for k in nc_keys]
            f.write(
                self._render_chartjs(
                    "chart-contributor-growth",
                    "bar",
                    nc_keys,
                    [{"label": "New contributors", "data": nc_values}],
                    y_label="New contributors",
                    x_ticks_rotate=True,
                    aspect_ratio=4,
                )
            )

        self.print_footer(f)
        f.write("</body></html>")
        f.close()

    def create_files_html(self, data: Any, path: str) -> None:
        ###
        # Files
        f = open(path + "/files.html", "w", encoding="utf-8")
        self.print_header(f)
        self.print_nav(f)
        f.write("<h1>Files</h1>")

        f.write("<dl>\n")
        f.write("<dt>Total files</dt><dd>%d</dd>" % data.get_total_files())
        f.write("<dt>Total lines</dt><dd>%d</dd>" % data.get_total_loc())
        try:
            f.write(
                "<dt>Average file size</dt><dd>%.2f bytes</dd>"
                % (float(data.get_total_size()) / data.get_total_files())
            )
        except ZeroDivisionError:
            pass
        f.write("</dl>\n")

        # Files :: File count by date
        f.write(html_header(2, "File count by date"))

        # use set to get rid of duplicate/unnecessary entries, then sort
        files_by_date = {}
        for stamp in sorted(data.files_by_stamp.keys()):
            date_str = datetime.datetime.fromtimestamp(stamp).strftime("%Y-%m-%d")
            files_by_date[date_str] = data.files_by_stamp[stamp]

        fbd_labels = sorted(files_by_date.keys())
        fbd_values = [files_by_date[d] for d in fbd_labels]
        f.write(
            self._render_chartjs(
                "chart-files-by-date",
                "line",
                fbd_labels,
                [{"label": "Files", "data": fbd_values}],
                y_label="Files",
                x_ticks_rotate=True,
            )
        )

        # f.write('<h2>Average file size by date</h2>')

        # Files :: Extensions
        f.write(html_header(2, "Extensions"))
        f.write(
            "<p><em>Note: Files with excluded extensions are not shown. Configure <code>exclude_exts</code> in gitstats.conf.</em></p>"
        )
        f.write(
            '<table class="sortable" id="ext"><tr><th>Extension</th><th>Files (%)</th><th>Lines (%)</th><th>Lines/file</th></tr>'
        )

        for ext in sorted(data.extensions.keys()):
            files = data.extensions[ext]["files"]
            lines = data.extensions[ext]["lines"]
            try:
                loc_percentage = (100.0 * lines) / data.get_total_loc()
            except ZeroDivisionError:
                loc_percentage = 0
            f.write(
                "<tr><td>%s</td><td>%d (%.2f%%)</td><td>%d (%.2f%%)</td><td>%d</td></tr>"
                % (
                    ext,
                    files,
                    (100.0 * files) / data.get_total_files(),
                    lines,
                    loc_percentage,
                    lines / files,
                )
            )
        f.write("</table>")

        # Files :: Code Churn (most frequently changed files)
        if data.file_churn:
            f.write(html_header(2, "Most Changed Files (Code Churn)"))
            f.write(
                "<p><em>Files touched most often across all commits. "
                "High-churn files are hotspots that may benefit from extra review or refactoring.</em></p>"
            )
            churn_sorted = sorted(data.file_churn.items(), key=lambda x: x[1], reverse=True)
            top_churn = churn_sorted[:25]
            max_churn = max(1, top_churn[0][1]) if top_churn else 1
            churn_labels = [item[0] for item in top_churn]
            churn_values = [item[1] for item in top_churn]
            f.write(
                '<table class="sortable" id="churn"><tr><th>File</th><th>Times Changed</th></tr>'
            )
            for filepath, count in top_churn:
                f.write(
                    '<tr><td class="%s">%s</td><td>%d</td></tr>'
                    % (
                        self._heat_td_class(count, max_churn),
                        html.escape(filepath),
                        count,
                    )
                )
            f.write("</table>")
            f.write(
                self._render_chartjs(
                    "chart-file-churn",
                    "bar",
                    churn_labels,
                    [{"label": "Commits", "data": churn_values}],
                    y_label="Times Changed",
                    x_ticks_rotate=True,
                    aspect_ratio=3,
                )
            )

        self.print_footer(f)
        f.write("</body></html>")
        f.close()

    def create_lines_html(self, data: Any, path: str) -> None:
        ###
        # Lines
        f = open(path + "/lines.html", "w", encoding="utf-8")
        self.print_header(f)
        self.print_nav(f)
        f.write("<h1>Lines</h1>")

        f.write("<dl>\n")
        f.write("<dt>Total lines</dt><dd>%d</dd>" % data.get_total_loc())
        f.write("</dl>\n")

        f.write(html_header(2, "Lines of Code"))
        loc_stamps = sorted(data.changes_by_date.keys())
        loc_labels = [datetime.datetime.fromtimestamp(s).strftime("%Y-%m-%d") for s in loc_stamps]
        loc_values = [data.changes_by_date[s]["lines"] for s in loc_stamps]
        f.write(
            self._render_chartjs(
                "chart-lines-of-code",
                "line",
                loc_labels,
                [{"label": "Lines", "data": loc_values}],
                y_label="Lines",
                x_ticks_rotate=True,
            )
        )

        self.print_footer(f)
        f.write("</body></html>")
        f.close()

    def create_tags_html(self, data: Any, path: str) -> None:
        ###
        # tags.html
        f = open(path + "/tags.html", "w", encoding="utf-8")
        self.print_header(f)
        self.print_nav(f)
        f.write("<h1>Tags</h1>")

        f.write("<dl>")
        f.write("<dt>Total tags</dt><dd>%d</dd>" % len(data.tags))
        if len(data.tags) > 0:
            f.write(
                "<dt>Average commits per tag</dt><dd>%.2f</dd>"
                % (1.0 * data.get_total_commits() / len(data.tags))
            )
        f.write("</dl>")

        f.write('<table class="tags">')
        f.write("<tr><th>Name</th><th>Date</th><th>Commits</th><th>Authors</th></tr>")
        # sort the tags by date desc
        tags_sorted_by_date_desc = [
            el[1]
            for el in sorted([(el[1]["date"], el[0]) for el in data.tags.items()], reverse=True)
        ]
        max_tags_authors = load_config()["max_tags_authors"]
        for tag in tags_sorted_by_date_desc:
            authorinfo = []
            self.authors_by_commits = get_keys_sorted_by_values(data.tags[tag]["authors"])
            authors_reversed = list(reversed(self.authors_by_commits))
            # max_tags_authors < 0 (e.g., -1) means no limit
            if max_tags_authors >= 0 and len(authors_reversed) > max_tags_authors:
                authors_shown = authors_reversed[:max_tags_authors]
                remaining = len(authors_reversed) - max_tags_authors
                for i in authors_shown:
                    authorinfo.append("%s (%d)" % (i, data.tags[tag]["authors"][i]))
                authorinfo.append("<em>and %d more authors</em>" % remaining)
            else:
                for i in authors_reversed:
                    authorinfo.append("%s (%d)" % (i, data.tags[tag]["authors"][i]))
            f.write(
                "<tr><td>%s</td><td>%s</td><td>%d</td><td>%s</td></tr>"
                % (
                    tag,
                    data.tags[tag]["date"],
                    data.tags[tag]["commits"],
                    ", ".join(authorinfo),
                )
            )
        f.write("</table>")

        self.print_footer(f)
        f.write("</body></html>")
        f.close()

    def _open_report_file(self, path: str, filename: str) -> Any:
        """Open a report page for writing, confined to the report directory.

        ``filename`` is always a hard-coded page name; resolving the target and
        checking it stays under the report root guards against directory
        traversal.
        """
        base = os.path.abspath(path)
        target = os.path.abspath(os.path.join(base, filename))
        if os.path.commonpath([base, target]) != base:
            raise ValueError(f"Refusing to write outside report directory: {filename}")
        return open(target, "w", encoding="utf-8")

    def create_ownership_html(self, data: Any, path: str) -> None:
        """Create the Code Ownership page.

        Turns the per-author file-edit data into actionable views: files with a
        single owner (bus-factor / knowledge-silo risk), how ownership is
        concentrated per author, and the files touched by the most people
        (coordination hotspots).
        """
        f = self._open_report_file(path, "ownership.html")
        self.print_header(f)
        self.print_nav(f)
        f.write("<h1>Code Ownership</h1>")

        author_files = getattr(data, "author_files", {})
        if not isinstance(author_files, dict):
            author_files = {}
        ownership = compute_code_ownership(author_files)

        if not ownership["files"]:
            f.write(
                '<div class="ownership-summary"><p>No ownership data available. '
                "Ownership is derived from which files each author changes; try "
                "analyzing a repository with commit history.</p></div>"
            )
            self.print_footer(f)
            f.write("</body></html>")
            f.close()
            return

        total = ownership["total_files"]
        single = ownership["single_owner_files"]
        single_pct = (100.0 * single / total) if total else 0.0

        # Summary
        f.write(
            '<div class="ownership-summary">'
            "<p>Ownership is measured by how many commits each author made to each "
            "file. It highlights <strong>bus-factor risk</strong> (files only one "
            "person has ever touched) and where knowledge is concentrated.</p>"
            "<dl>"
            "<dt>Files tracked</dt><dd>%d</dd>"
            "<dt>Single-owner files</dt><dd>%d (%.1f%%)</dd>"
            "<dt>Contributors</dt><dd>%d</dd>"
            "</dl></div>" % (total, single, single_pct, len(ownership["authors"]))
        )

        # Bus-factor risk: single-owner files, most-changed first
        f.write(html_header(2, "Bus Factor Risk — Single-Owner Files"))
        f.write(
            "<p><em>Files only one author has ever changed. The more a file has "
            "changed, the more knowledge is at risk if that person leaves.</em></p>"
        )
        risk_files = [fs for fs in ownership["files"] if fs["contributors"] == 1]
        if risk_files:
            f.write(
                '<table class="sortable" id="ownership-busfactor">'
                "<tr><th>File</th><th>Sole owner</th><th>Commits</th></tr>"
            )
            for fs in risk_files[:50]:
                f.write(
                    "<tr><td>%s</td><td>%s</td><td>%d</td></tr>"
                    % (html.escape(fs["path"]), html.escape(fs["owner"]), fs["edits"])
                )
            f.write("</table>")
            if len(risk_files) > 50:
                f.write(
                    '<p class="moreauthors">Showing top 50 of %d single-owner files.</p>'
                    % len(risk_files)
                )
        else:
            f.write("<p>No single-owner files — every file has multiple contributors.</p>")

        # Ownership concentration by author
        f.write(html_header(2, "Ownership by Author"))
        f.write(
            "<p><em>Primary owner = the author with the most commits to a file. "
            "Solely owned = files only that author has touched.</em></p>"
        )
        f.write(
            '<table class="sortable" id="ownership-by-author">'
            "<tr><th>Author</th><th>Files owned</th><th>Solely owned</th>"
            "<th>Files touched</th></tr>"
        )
        for a in ownership["authors"][:25]:
            f.write(
                "<tr><td>%s</td><td>%d</td><td>%d</td><td>%d</td></tr>"
                % (
                    html.escape(a["author"]),
                    a["files_owned"],
                    a["files_solely_owned"],
                    a["files_touched"],
                )
            )
        f.write("</table>")
        if len(ownership["authors"]) > 25:
            f.write(
                '<p class="moreauthors">Showing top 25 of %d contributors.</p>'
                % len(ownership["authors"])
            )

        # Coordination hotspots: files with the most contributors
        f.write(html_header(2, "Most Shared Files"))
        f.write(
            "<p><em>Files touched by the most people — shared code where changes "
            "are most likely to need coordination.</em></p>"
        )
        shared = sorted(
            (fs for fs in ownership["files"] if fs["contributors"] >= 2),
            key=lambda x: (x["contributors"], x["edits"]),
            reverse=True,
        )
        if shared:
            f.write(
                '<table class="sortable" id="ownership-shared">'
                "<tr><th>File</th><th>Contributors</th><th>Primary owner</th>"
                "<th>Owner share</th></tr>"
            )
            for fs in shared[:20]:
                f.write(
                    "<tr><td>%s</td><td>%d</td><td>%s</td><td>%.1f%%</td></tr>"
                    % (
                        html.escape(fs["path"]),
                        fs["contributors"],
                        html.escape(fs["owner"]),
                        fs["ownership_pct"],
                    )
                )
            f.write("</table>")
        else:
            f.write("<p>No files have more than one contributor yet.</p>")

        self.print_footer(f)
        f.write("</body></html>")
        f.close()

    _ERA_DESCRIPTIONS = {
        "birth": "first commits",
        "peak": "busiest year",
        "surge": "well above the usual pace",
        "revival": "active again after a lull",
        "quiet": "well below the usual pace",
        "dormant": "no commits",
        "steady": "",
    }

    def create_history_html(self, data: Any, path: str) -> None:
        """Create the History page: the project's life, one year at a time.

        A deterministic timeline derived entirely from already-collected data:
        each year is classified against the repository's own baseline (birth,
        peak, surge, quiet, dormant, revival), and carries its commit volume,
        the year's leading author, the contributors who made their first
        commit that year, and the releases tagged in it.
        """
        f = self._open_report_file(path, "history.html")
        self.print_header(f)
        self.print_nav(f)
        f.write("<h1>History</h1>")

        history = compute_project_history(data)
        years = history["years"]

        if not years:
            f.write(
                '<div class="history-summary"><p>No history to tell yet — '
                "this repository has no commits in the analyzed range.</p></div>"
            )
            self.print_footer(f)
            f.write("</body></html>")
            f.close()
            return

        span = history["last_year"] - history["first_year"] + 1
        f.write(
            '<div class="history-summary">'
            "<p>The project's life, one year at a time, told from the commit "
            "record: how activity rose and fell against the project's own "
            "baseline, who arrived when, and what was released.</p>"
            "<dl>"
            "<dt>Span</dt><dd>%d – %d (%d year%s)</dd>"
            "<dt>Peak year</dt><dd>%d</dd>"
            "<dt>Releases</dt><dd>%d</dd>"
            "</dl></div>"
            % (
                history["first_year"],
                history["last_year"],
                span,
                "s" if span != 1 else "",
                history["peak_year"],
                history["total_releases"],
            )
        )

        max_commits = max(y["commits"] for y in years)
        for entry in years:
            era = entry["era"]
            desc = self._ERA_DESCRIPTIONS.get(era, "")
            bar_pct = round(100.0 * entry["commits"] / max_commits, 1) if max_commits else 0.0

            f.write('<div class="history-year">')
            f.write(
                '<div class="history-year-head">'
                '<span class="history-year-num">%d</span>'
                '<span class="history-era history-era-%s">%s</span>'
                "%s</div>"
                % (
                    entry["year"],
                    era,
                    era.upper(),
                    f'<span class="history-era-desc">{desc}</span>' if desc else "",
                )
            )
            f.write(
                '<div class="history-bar-track"><div class="history-bar" '
                'style="width:%s%%"></div></div>' % bar_pct
            )

            if entry["commits"]:
                facts = "%d commits (%s%%) &middot; +%d / &minus;%d lines &middot; %d author%s" % (
                    entry["commits"],
                    entry["commits_pct"],
                    entry["lines_added"],
                    entry["lines_removed"],
                    entry["active_authors"],
                    "s" if entry["active_authors"] != 1 else "",
                )
                f.write(f'<p class="history-facts">{facts}</p>')
                if entry["top_author"]:
                    f.write(
                        '<p class="history-people">Led by <strong>%s</strong> (%d commits)</p>'
                        % (html.escape(entry["top_author"]), entry["top_author_commits"])
                    )
                if entry["newcomers"]:
                    f.write(
                        '<p class="history-people">First commits: %s%s</p>'
                        % (
                            ", ".join(html.escape(n) for n in entry["newcomers"][:6]),
                            " (+%d more)" % (len(entry["newcomers"]) - 6)
                            if len(entry["newcomers"]) > 6
                            else "",
                        )
                    )
                if entry["releases"]:
                    f.write(
                        '<p class="history-people">Released: %s%s</p>'
                        % (
                            ", ".join(html.escape(t) for t in entry["releases"][:5]),
                            " (+%d more)" % (len(entry["releases"]) - 5)
                            if len(entry["releases"]) > 5
                            else "",
                        )
                    )
            else:
                f.write('<p class="history-facts">No commits this year.</p>')
            f.write("</div>")

        self.print_footer(f)
        f.write("</body></html>")
        f.close()

    def create_ai_insights_html(self, data: Any, path: str) -> None:
        """
        Create a dedicated AI Insights page with all AI-generated summaries.
        """
        # Get language from config
        language = load_config().get("ai_language", "en")

        f = open(path + "/ai-insights.html", "w", encoding="utf-8")
        self.print_header(f)
        self.print_nav(f)
        f.write(f"<h1>{get_i18n_text('ai_insights_title', language)}</h1>")

        f.write(f"""
        <div class="ai-insights-intro">
            <p>{get_i18n_text("ai_insights_intro", language)}</p>
        </div>
        """)

        # Get all AI summaries
        summaries = data.ai_summaries

        # Define sections with titles and descriptions
        sections = [
            {
                "key": "index",
                "title": get_i18n_text("project_overview", language),
                "description": get_i18n_text("project_overview_desc", language),
            },
            {
                "key": "activity",
                "title": get_i18n_text("activity_patterns", language),
                "description": get_i18n_text("activity_patterns_desc", language),
            },
            {
                "key": "lines",
                "title": get_i18n_text("code_evolution", language),
                "description": get_i18n_text("code_evolution_desc", language),
            },
        ]

        # Generate sections
        for section in sections:
            key = section["key"]
            if key not in summaries:
                continue

            summary_data = summaries[key]
            summary_text = summary_data.get("summary", "")
            error = summary_data.get("error")

            f.write('<div class="ai-insight-section">')
            f.write(f'<h2 id="{key}">{section["title"]}</h2>')
            f.write(f'<p class="section-description"><em>{section["description"]}</em></p>')

            if error:
                f.write(f"""
                <div class="ai-summary-error">
                    <p><strong>{get_i18n_text("analysis_unavailable", language)}</strong></p>
                    <p><em>{error}</em></p>
                </div>
                """)
            elif summary_text:
                f.write(f"""
                <div class="ai-summary-content">
                    {summary_text}
                </div>
                """)
            else:
                f.write(f"<p><em>{get_i18n_text('no_analysis', language)}</em></p>")

            f.write("</div>")

        # Add disclaimer
        f.write(f"""
        <div class="ai-disclaimer">
            <h3>{get_i18n_text("about_ai_insights", language)}</h3>
            <p>{get_i18n_text("ai_disclaimer", language)}</p>
            <p>{get_i18n_text("bot_note", language)}</p>
        </div>
        """)

        self.print_footer(f)
        f.write("</body></html>")
        f.close()

    CHART_COLORS = ["#5b8dee", "#1a7f37", "#cf222e", "#8250df", "#e16f24", "#0550ae"]

    def _render_chartjs(
        self,
        chart_id,
        chart_type,
        labels,
        datasets,
        y_label="Commits",
        x_ticks_rotate=False,
        aspect_ratio=3,
        max_bar_thickness=None,
    ):
        """Render a Chart.js chart as inline HTML."""
        is_multi = len(datasets) > 1

        js_datasets = []
        for i, ds in enumerate(datasets):
            color = self.CHART_COLORS[i % len(self.CHART_COLORS)]
            entry = dict(ds)
            if is_multi:
                entry.setdefault("borderColor", color)
                entry.setdefault("backgroundColor", color + "33")
                entry.setdefault("fill", False)
                entry.setdefault("tension", 0.1)
                entry.setdefault("pointRadius", 2)
                entry.setdefault("borderWidth", 1)
            else:
                # single dataset: use CSS var for theme-aware color
                entry["backgroundColor"] = "__CSS_BAR_COLOR__"
                entry["borderColor"] = "__CSS_BAR_COLOR__"
                if chart_type == "line":
                    entry.setdefault("borderWidth", 1)
                    entry.setdefault("pointRadius", 2)
            js_datasets.append(entry)

        labels_json = json.dumps(labels).replace("</", "<\\/")
        datasets_json = json.dumps(js_datasets).replace("</", "<\\/")
        # Replace quoted placeholder with JS expression
        datasets_json = datasets_json.replace('"__CSS_BAR_COLOR__"', "getCSSVar('--bar-color')")

        x_ticks_opts = "maxRotation: 45, minRotation: 45" if x_ticks_rotate else "maxRotation: 0"
        legend_display = "true" if is_multi else "false"

        return f"""<div style="max-width:100%;margin-bottom:8px"><canvas id="{chart_id}"></canvas></div>
<script>
(function() {{
  var ctx = document.getElementById('{chart_id}').getContext('2d');
  var chart = new Chart(ctx, {{
    type: '{chart_type}',
    data: {{
      labels: {labels_json},
      datasets: {datasets_json}
    }},
    options: {{
      responsive: true,
      maintainAspectRatio: true,
      aspectRatio: {aspect_ratio},
      plugins: {{
        legend: {{ display: {legend_display} }}
      }},
      scales: {{
        x: {{ ticks: {{ {x_ticks_opts} }} }},
        y: {{ beginAtZero: true, title: {{ display: true, text: '{y_label}' }} }}
      }}{f", datasets: {{ bar: {{ maxBarThickness: {max_bar_thickness} }} }}" if max_bar_thickness else ""}
    }}
  }});
  document.addEventListener('themechange', function() {{ chart.update(); }});
}})();
</script>
"""

    def print_footer(self, file: Any) -> None:
        """
        Write the HTML page footer with a "Generated by gitstats" link.

        Parameters:
            file: A writable file-like object opened in text mode.
        """
        file.write(
            '<div class="footer">'
            '<span class="footer-generated">Generated by '
            '<a href="https://github.com/shenxianpeng/gitstats" target="_blank" rel="noopener">gitstats</a>'
            "</span>"
            "</div>\n"
        )

    def print_header(self, file: Any) -> None:
        """
        Write the HTML document header and opening body tag into the provided writable file.

        This writes the DOCTYPE, head section (title from self.title), a link to the configured stylesheet, a generator meta tag, an inclusion of sortable.js, an embedded client-side theme toggle script (init, toggle, and icon update handlers using localStorage), and the opening <body> tag.

        Parameters:
                file: A writable file-like object opened for text output where the HTML header will be written.
        """
        file.write(
            """<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>GitStats - {}</title>
	<!-- Apply theme before CSS loads to prevent flash of unstyled content -->
	<script>(function(){{var t=localStorage.getItem('theme')||'light';document.documentElement.setAttribute('data-theme',t);}})();</script>
	<link rel="stylesheet" href="{}" type="text/css">
	<meta name="generator" content="GitStats {}">
	<script type="text/javascript" src="sortable.js"></script>
	<script type="text/javascript" src="chart.umd.min.js"></script>
	<script>
		function getCSSVar(v) {{ return getComputedStyle(document.documentElement).getPropertyValue(v).trim(); }}

		function toggleTheme() {{
			const currentTheme = document.documentElement.getAttribute('data-theme');
			const newTheme = currentTheme === 'dark' ? 'light' : 'dark';
			document.documentElement.setAttribute('data-theme', newTheme);
			localStorage.setItem('theme', newTheme);
			updateThemeIcon(newTheme);
		}}

		function updateThemeIcon(theme) {{
			const button = document.getElementById('theme-toggle');
			if (button) {{
				button.innerHTML = theme === 'dark' ? '☀️' : '🌙';
				button.setAttribute('aria-label', theme === 'dark' ? 'Switch to light mode' : 'Switch to dark mode');
			}}
		}}

		document.addEventListener('DOMContentLoaded', function() {{
			updateThemeIcon(document.documentElement.getAttribute('data-theme'));
		}});
	</script>
</head>
<body>
""".format(self.title, load_config()["style"], get_version)
        )

    def print_nav(self, file: Any) -> None:
        """
        Write the navigation bar HTML (page links and a client-side theme-toggle button) to the given writable file-like object.

        Parameters:
            file: A writable file-like object opened in text mode where the navigation HTML will be written.
        """
        # Check if AI insights are available
        has_ai = hasattr(self.data, "ai_summaries") and self.data.ai_summaries

        ai_link = '<li><a href="ai-insights.html">AI Insights</a></li>' if has_ai else ""

        github_icon = (
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="20" height="20" '
            'fill="currentColor" aria-hidden="true">'
            '<path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 '
            "0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15"
            "-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07"
            "-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 "
            ".67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82"
            ".44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25"
            ".54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8"
            'c0-4.42-3.58-8-8-8z"/></svg>'
        )

        file.write(
            f"""
            <div class="nav">
            <a href="index.html" class="nav-brand">GitStats</a>
            <ul>
            <li><a href="index.html">General</a></li>
            <li><a href="activity.html">Activity</a></li>
            <li><a href="authors.html">Authors</a></li>
            <li><a href="files.html">Files</a></li>
            <li><a href="lines.html">Lines</a></li>
            <li><a href="tags.html">Tags</a></li>
            <li><a href="ownership.html">Code Ownership</a></li>
            <li><a href="history.html">History</a></li>
            {ai_link}
            </ul>
            <div class="nav-right">
            <a href="https://github.com/shenxianpeng/gitstats" class="nav-github" target="_blank" rel="noopener" aria-label="GitHub">{github_icon}</a>
            <button id="theme-toggle" class="theme-toggle" onclick="toggleTheme()" aria-label="Switch to dark mode">🌙</button>
            </div>
            </div>
            """
        )

    def get_ai_summary_html(self, page_type: str) -> str:
        """
        Generate HTML for AI-powered summary section.

        Args:
            page_type: The type of page (index, activity, authors, lines)

        Returns:
            HTML string for the AI summary section
        """
        if not hasattr(self.data, "ai_summaries") or not self.data.ai_summaries:
            return ""

        summary_data = self.data.ai_summaries.get(page_type, {})
        summary_text = summary_data.get("summary", "")
        error = summary_data.get("error")

        if error:
            # Show error message with graceful degradation
            return f"""
            <div class="ai-summary ai-summary-error">
                <h3>AI Insights</h3>
                <p><em>AI analysis is currently unavailable: {error}</em></p>
            </div>
            """

        if not summary_text:
            return ""

        return f"""
        <div class="ai-summary">
            <h3>AI-Powered Insights</h3>
            <div class="ai-summary-content">
                {summary_text}
            </div>
        </div>
        """


def compute_code_ownership(author_files: dict[str, dict[str, int]]) -> dict[str, Any]:
    """Derive per-file ownership and per-author stats from author edit counts.

    Args:
        author_files: mapping of author -> file path -> number of commits that
            author made touching the file.

    Bot accounts (names ending in ``[bot]``) are excluded so ownership reflects
    human contributors. Returns a dict with:
        files:   per-file stats (path, edits, owner, owner_edits, ownership_pct,
                 contributors), sorted by edits descending;
        authors: per-author stats (author, files_owned, files_solely_owned,
                 files_touched), sorted by files owned then files touched;
        total_files, single_owner_files.
    """
    # Invert to file -> {author: edits}, dropping bots.
    file_authors: dict[str, dict[str, int]] = {}
    for author, files in author_files.items():
        if author.endswith("[bot]"):
            continue
        for filepath, count in files.items():
            file_authors.setdefault(filepath, {})[author] = count

    files_stats: list[dict[str, Any]] = []
    author_owned: dict[str, int] = {}
    author_solely: dict[str, int] = {}
    author_touched: dict[str, int] = {}
    for filepath, authors in file_authors.items():
        edits = sum(authors.values())
        # Primary owner: most edits; ties broken alphabetically for determinism.
        owner = max(zip(authors.values(), authors.keys()))[1]
        contributors = len(authors)
        files_stats.append(
            {
                "path": filepath,
                "edits": edits,
                "owner": owner,
                "owner_edits": authors[owner],
                "ownership_pct": round(100.0 * authors[owner] / edits, 1) if edits else 0.0,
                "contributors": contributors,
            }
        )
        author_owned[owner] = author_owned.get(owner, 0) + 1
        if contributors == 1:
            author_solely[owner] = author_solely.get(owner, 0) + 1
        for a in authors:
            author_touched[a] = author_touched.get(a, 0) + 1

    files_stats.sort(key=lambda x: x["edits"], reverse=True)

    authors_stats = [
        {
            "author": a,
            "files_owned": author_owned.get(a, 0),
            "files_solely_owned": author_solely.get(a, 0),
            "files_touched": author_touched[a],
        }
        for a in author_touched
    ]
    authors_stats.sort(key=lambda x: (x["files_owned"], x["files_touched"]), reverse=True)

    return {
        "files": files_stats,
        "authors": authors_stats,
        "total_files": len(files_stats),
        "single_owner_files": sum(1 for fs in files_stats if fs["contributors"] == 1),
    }


def _classify_eras(year_commits: dict[int, int]) -> dict[int, str]:
    """Assign each year of the project's span one era label.

    Labels are relative to the repository's own baseline (the median of its
    non-zero years), so a "surge" in a small project and in a huge one mean
    the same thing: well above what is normal *for that project*. The span is
    contiguous — years without commits appear as "dormant" instead of being
    skipped, because silence is part of the story.

    Priority per year: birth > dormant > peak > revival > surge > quiet > steady.
    """
    if not year_commits:
        return {}
    first, last = min(year_commits), max(year_commits)
    span = {y: year_commits.get(y, 0) for y in range(first, last + 1)}
    active = [c for c in span.values() if c > 0]
    med = sorted(active)[len(active) // 2]
    peak_year = max(span, key=lambda y: (span[y], y))
    # With under three active years there is no meaningful baseline to
    # compare against, so only the structural labels apply.
    tiny = len(active) < 3

    eras: dict[int, str] = {}
    prev = ""
    for y in sorted(span):
        c = span[y]
        if y == first:
            era = "birth"
        elif c == 0:
            era = "dormant"
        elif y == peak_year and not tiny:
            era = "peak"
        elif prev in ("dormant", "quiet") and c >= med:
            era = "revival"
        elif not tiny and c >= 1.6 * med:
            era = "surge"
        elif not tiny and c <= 0.35 * med:
            era = "quiet"
        else:
            era = "steady"
        eras[y] = era
        prev = era
    return eras


def compute_project_history(data: Any) -> dict[str, Any]:
    """Derive a chronological, per-year account of the project from collected data.

    Everything here is computed from data the collector already gathered —
    no extra git traffic. Bot accounts (names ending in ``[bot]``) are left
    out of the people-facing fields. Returns a dict with:
        years: one entry per calendar year of the span (gap years included),
               each carrying commits, line deltas, author counts, the top
               author, newcomers (authors whose first commit fell in that
               year, most active first) and the releases tagged that year;
        first_year, last_year, peak_year, total_releases.
    """
    year_commits: dict[int, int] = dict(getattr(data, "commits_by_year", {}) or {})
    if not year_commits:
        return {
            "years": [],
            "first_year": None,
            "last_year": None,
            "peak_year": None,
            "total_releases": 0,
        }

    eras = _classify_eras(year_commits)
    author_of_year = getattr(data, "author_of_year", {}) or {}
    lines_added = getattr(data, "lines_added_by_year", {}) or {}
    lines_removed = getattr(data, "lines_removed_by_year", {}) or {}

    # Authors whose first commit fell in each year (bots excluded).
    newcomers_by_year: dict[int, list[str]] = {}
    for name, info in (getattr(data, "authors", {}) or {}).items():
        stamp = info.get("first_commit_stamp") if isinstance(info, dict) else None
        if not stamp or name.endswith("[bot]"):
            continue
        yy = datetime.datetime.fromtimestamp(stamp).year
        newcomers_by_year.setdefault(yy, []).append(name)

    # Releases (tags) by the year they were made.
    releases_by_year: dict[int, list[tuple[str, str]]] = {}
    total_releases = 0
    for tag, info in (getattr(data, "tags", {}) or {}).items():
        date = str(info.get("date", ""))
        if len(date) >= 4 and date[:4].isdigit():
            releases_by_year.setdefault(int(date[:4]), []).append((date, tag))
            total_releases += 1

    total_commits = sum(year_commits.values())
    years: list[dict[str, Any]] = []
    for y in sorted(eras):
        commits = year_commits.get(y, 0)
        year_authors = author_of_year.get(y, {})
        humans = {a: c for a, c in year_authors.items() if not a.endswith("[bot]")}
        ranked = sorted(humans or year_authors, key=lambda a: (year_authors[a], a), reverse=True)
        top_author = ranked[0] if ranked else ""
        newcomers = sorted(
            newcomers_by_year.get(y, []),
            key=lambda a: (year_authors.get(a, 0), a),
            reverse=True,
        )
        years.append(
            {
                "year": y,
                "era": eras[y],
                "commits": commits,
                "commits_pct": round(100.0 * commits / total_commits, 1) if total_commits else 0.0,
                "lines_added": lines_added.get(y, 0),
                "lines_removed": lines_removed.get(y, 0),
                "active_authors": len(year_authors),
                "top_author": top_author,
                "top_author_commits": year_authors.get(top_author, 0),
                "newcomers": newcomers,
                "releases": [t for _, t in sorted(releases_by_year.get(y, []))],
            }
        )

    return {
        "years": years,
        "first_year": years[0]["year"],
        "last_year": years[-1]["year"],
        "peak_year": max(year_commits, key=lambda y: (year_commits[y], y)),
        "total_releases": total_releases,
    }


def html_header(level: int, text: str) -> str:
    name = html_linkify(text)
    return '\n<h%d id="%s"><a href="#%s">%s</a></h%d>\n\n' % (
        level,
        name,
        name,
        text,
        level,
    )


def html_linkify(text: str) -> str:
    return text.lower().replace(" ", "_")


def get_keys_sorted_by_values(d: dict[str, int]) -> list[str]:
    return [el[1] for el in sorted([(el[1], el[0]) for el in d.items()])]


# dict['author'] = { 'commits': 512 } - ...key(dict, 'commits')
def get_keys_sorted_by_value_key(d: dict[str, dict[str, Any]], key: str) -> list[str]:
    return [el[1] for el in sorted([(d[el][key], el) for el in d.keys()])]
