# Copyright (c) 2007-2014 Heikki Hokkanen <hoxu@users.sf.net> & others contributors
# GPLv2 / GPLv3
# Copyright (c) 2024-present Xianpeng Shen <xianpeng.shen@gmail.com>.
# GPLv2 / GPLv3
import os
import shutil
import datetime
import time
import math
import json
from gitstats import load_config, WEEKDAYS, get_i18n_text
from gitstats.utils import (
    get_version,
    get_git_version,
    get_pipe_output,
)

conf = load_config()


class ReportCreator:
    """Creates the actual report based on given data."""

    def __init__(self):
        self.data = None
        self.path = None

    def create(self, data, path):
        self.data = data
        self.path = path


class HTMLReportCreator(ReportCreator):
    @staticmethod
    def _heat_level(value, max_value):
        if max_value <= 0 or value <= 0:
            return 0
        ratio = float(value) / float(max_value)
        if ratio <= 0.25:
            return 1
        if ratio <= 0.50:
            return 2
        if ratio <= 0.75:
            return 3
        return 4

    @classmethod
    def _heat_td_class(cls, value, max_value):
        return f"heat heat{cls._heat_level(value, max_value)}"

    def create(self, data, path):
        ReportCreator.create(self, data, path)
        self.title = data.project_name

        # copy static files to the report directory
        basedir = os.path.dirname(os.path.abspath(__file__))
        for file in (
            conf["style"],
            "sortable.js",
            "chart.umd.min.js",
            "arrow-up.gif",
            "arrow-down.gif",
            "arrow-none.gif",
        ):
            src = basedir + "/" + file
            if os.path.exists(src):
                shutil.copyfile(src, path + "/" + file)

        self.create_index_html(data, path)
        self.create_activity_html(data, path)
        self.create_authors_html(data, path)
        self.create_files_html(data, path)
        self.create_lines_html(data, path)
        self.create_tags_html(data, path)

        # Create AI Insights page if AI is enabled
        if hasattr(data, "ai_summaries") and data.ai_summaries:
            self.create_ai_insights_html(data, path)

    def create_index_html(self, data, path):
        f = open(path + "/index.html", "w", encoding="utf-8")
        format = "%Y-%m-%d %H:%M:%S"
        self.print_header(f)

        self.print_nav(f)

        f.write("<h1>General</h1>")

        f.write(html_header(2, "Git Overview"))

        f.write("<table border='1' cellspacing='0' cellpadding='4'>")
        f.write("<tr><td>Project Name</td><td>%s</td></tr>" % data.project_name)
        f.write(
            "<tr><td>Generated On</td><td>%s (in %d seconds)</td></tr>"
            % (
                datetime.datetime.now().strftime(format),
                time.time() - data.get_stamp_created(),
            )
        )
        f.write(
            '<tr><td>Generated By</td><td><a href="https://github.com/shenxianpeng/gitstats">gitstats</a> %s, %s</td></tr>'
            % (get_version(), get_git_version())
        )
        f.write(
            "<tr><td>Report Period</td><td>%s to %s</td></tr>"
            % (
                data.get_first_commit_date().strftime(format),
                data.get_last_commit_date().strftime(format),
            )
        )
        f.write(
            "<tr><td>Project Age</td><td>%d days, %d active days (%3.2f%%)</td></tr>"
            % (
                data.get_commit_delta_days(),
                len(data.get_active_days()),
                (100.0 * len(data.get_active_days()) / data.get_commit_delta_days()),
            )
        )
        f.write("<tr><td>Total Files</td><td>%s</td></tr>" % data.get_total_files())
        f.write(
            "<tr><td>Total Lines of Code</td><td>%s (%d added, %d removed)</td></tr>"
            % (data.get_total_loc(), data.total_lines_added, data.total_lines_removed)
        )
        f.write(
            "<tr><td>Total Commits</td><td>%s (average %.1f commits per active day, %.1f per all days)</td></tr>"
            % (
                data.get_total_commits(),
                float(data.get_total_commits()) / len(data.get_active_days()),
                float(data.get_total_commits()) / data.get_commit_delta_days(),
            )
        )
        f.write(
            "<tr><td>Authors</td><td>%s (average %.1f commits per author)</td></tr>"
            % (
                data.get_total_authors(),
                (1.0 * data.get_total_commits()) / data.get_total_authors(),
            )
        )
        f.write("</table>")

        f.write("</body>\n</html>")
        f.close()

    def create_activity_html(self, data, path):
        ###
        # Activity
        f = open(path + "/activity.html", "w", encoding="utf-8")
        self.print_header(f)
        self.print_nav(f)
        f.write("<h1>Activity</h1>")

        # f.write('<h2>Last 30 days</h2>')

        # f.write('<h2>Last 12 months</h2>')

        # Yearly activity
        first_commit_timestamp = get_pipe_output(
            ["git log --reverse --pretty=format:%ct | head -n 1"], quiet=True
        )
        if first_commit_timestamp:
            repo_age_years = (
                time.time() - int(first_commit_timestamp)
            ) / 31536000  # 365 days
            YEARS = max(5, int(math.ceil(repo_age_years / 5.0)) * 5)
        else:
            YEARS = 5
        f.write(html_header(2, "Yearly activity"))
        f.write("<p>Last %d years</p>" % YEARS)

        # generate years to show (previous N years from now)
        now = datetime.datetime.now()
        deltayear = datetime.timedelta(365)
        years = []
        stampcur = now
        for i in range(0, YEARS):
            years.insert(0, stampcur.strftime("%Y"))
            stampcur -= deltayear

        yearly_values = [data.commits_by_year.get(int(y), 0) for y in years]
        f.write(
            self._render_chartjs(
                "chart-yearly-activity",
                "bar",
                years,
                [{"label": "Commits", "data": yearly_values}],
                y_label="Commits",
            )
        )

        # Weekly activity
        WEEKS = 32
        f.write(html_header(2, "Weekly activity"))
        f.write("<p>Last %d weeks</p>" % WEEKS)

        # generate weeks to show (previous N weeks from now)
        now = datetime.datetime.now()
        deltaweek = datetime.timedelta(7)
        weeks = []
        stampcur = now
        for i in range(0, WEEKS):
            weeks.insert(0, stampcur.strftime("%Y-%W"))
            stampcur -= deltaweek

        weekly_values = [data.activity_by_year_week.get(w, 0) for w in weeks]
        f.write(
            self._render_chartjs(
                "chart-weekly-activity",
                "bar",
                weeks,
                [{"label": "Commits", "data": weekly_values}],
                y_label="Commits",
                x_ticks_rotate=True,
                aspect_ratio=5,
            )
        )

        # Hour of Day
        f.write(html_header(2, "Hour of Day"))
        hour_of_day = data.get_activity_by_hour_of_day()
        f.write("<table><tr><th>Hour</th>")
        for i in range(0, 24):
            f.write("<th>%d</th>" % i)
        f.write("</tr>\n<tr><th>Commits</th>")
        for i in range(0, 24):
            if i in hour_of_day:
                f.write(
                    '<td class="%s">%d</td>'
                    % (
                        self._heat_td_class(
                            hour_of_day[i], data.activity_by_hour_of_day_busiest
                        ),
                        hour_of_day[i],
                    )
                )
            else:
                f.write('<td class="%s">0</td>' % self._heat_td_class(0, 0))
        f.write("</tr>\n<tr><th>%</th>")
        totalcommits = data.get_total_commits()
        for i in range(0, 24):
            if i in hour_of_day:
                f.write(
                    '<td class="%s">%.2f</td>'
                    % (
                        self._heat_td_class(
                            hour_of_day[i], data.activity_by_hour_of_day_busiest
                        ),
                        (100.0 * hour_of_day[i]) / totalcommits,
                    )
                )
            else:
                f.write('<td class="%s">0.00</td>' % self._heat_td_class(0, 0))
        f.write("</tr></table>")
        h_labels = list(range(0, 24))
        h_values = [hour_of_day.get(h, 0) for h in h_labels]
        f.write(
            self._render_chartjs(
                "chart-hour-of-day",
                "bar",
                h_labels,
                [{"label": "Commits", "data": h_values}],
                y_label="Commits",
            )
        )

        # Day of Week
        f.write(html_header(2, "Day of Week"))
        day_of_week = data.get_activity_by_day_of_week()
        f.write('<div class="vtable"><table>')
        f.write("<tr><th>Day</th><th>Total (%)</th></tr>")
        for d in range(0, 7):
            f.write("<tr>")
            f.write("<th>%s</th>" % (WEEKDAYS[d]))
            if d in day_of_week:
                f.write(
                    "<td>%d (%.2f%%)</td>"
                    % (day_of_week[d], (100.0 * day_of_week[d]) / totalcommits)
                )
            else:
                f.write("<td>0</td>")
            f.write("</tr>")
        f.write("</table></div>")
        dow_labels = list(WEEKDAYS)
        dow_values = [day_of_week.get(d, 0) for d in range(0, 7)]
        f.write(
            self._render_chartjs(
                "chart-day-of-week",
                "bar",
                dow_labels,
                [{"label": "Commits", "data": dow_values}],
                y_label="Commits",
            )
        )

        # Hour of Week
        f.write(html_header(2, "Hour of Week"))
        f.write("<table>")

        f.write("<tr><th>Weekday</th>")
        for hour in range(0, 24):
            f.write("<th>%d</th>" % (hour))
        f.write("</tr>")

        for weekday in range(0, 7):
            f.write("<tr><th>%s</th>" % (WEEKDAYS[weekday]))
            for hour in range(0, 24):
                try:
                    commits = data.activity_by_hour_of_week[weekday][hour]
                except KeyError:
                    commits = 0
                f.write(
                    '<td class="%s">%s</td>'
                    % (
                        self._heat_td_class(
                            commits, data.activity_by_hour_of_week_busiest
                        ),
                        ("%d" % commits) if commits != 0 else "",
                    )
                )
            f.write("</tr>")

        f.write("</table>")

        # Month of Year
        f.write(html_header(2, "Month of Year"))
        f.write('<div class="vtable"><table>')
        f.write("<tr><th>Month</th><th>Commits (%)</th></tr>")
        for mm in range(1, 13):
            commits = data.activity_by_month_of_year.get(mm, 0)
            f.write(
                "<tr><td>%d</td><td>%d (%.2f %%)</td></tr>"
                % (mm, commits, (100.0 * commits) / data.get_total_commits())
            )
        f.write("</table></div>")
        moy_labels = list(range(1, 13))
        moy_values = [data.activity_by_month_of_year.get(mm, 0) for mm in moy_labels]
        f.write(
            self._render_chartjs(
                "chart-month-of-year",
                "bar",
                moy_labels,
                [{"label": "Commits", "data": moy_values}],
                y_label="Commits",
            )
        )

        # Commits by year/month
        f.write(html_header(2, "Commits by year/month"))
        f.write(
            '<div class="vtable"><table><tr><th>Month</th><th>Commits</th><th>Lines added</th><th>Lines removed</th></tr>'
        )
        for yymm in reversed(sorted(data.commits_by_month.keys())):
            f.write(
                "<tr><td>%s</td><td>%d</td><td>%d</td><td>%d</td></tr>"
                % (
                    yymm,
                    data.commits_by_month.get(yymm, 0),
                    data.lines_added_by_month.get(yymm, 0),
                    data.lines_removed_by_month.get(yymm, 0),
                )
            )
        f.write("</table></div>")
        cbym_keys = sorted(data.commits_by_month.keys())
        cbym_values = [data.commits_by_month[k] for k in cbym_keys]
        f.write(
            self._render_chartjs(
                "chart-commits-by-year-month",
                "bar",
                cbym_keys,
                [{"label": "Commits", "data": cbym_values}],
                y_label="Commits",
                x_ticks_rotate=True,
            )
        )

        # Commits by year
        f.write(html_header(2, "Commits by Year"))
        f.write(
            '<div class="vtable"><table><tr><th>Year</th><th>Commits (% of all)</th><th>Lines added</th><th>Lines removed</th></tr>'
        )
        for yy in reversed(sorted(data.commits_by_year.keys())):
            f.write(
                "<tr><td>%s</td><td>%d (%.2f%%)</td><td>%d</td><td>%d</td></tr>"
                % (
                    yy,
                    data.commits_by_year.get(yy, 0),
                    (100.0 * data.commits_by_year.get(yy, 0))
                    / data.get_total_commits(),
                    data.lines_added_by_year.get(yy, 0),
                    data.lines_removed_by_year.get(yy, 0),
                )
            )
        f.write("</table></div>")
        if data.commits_by_year:
            cby_all_years = list(
                range(
                    min(data.commits_by_year.keys()),
                    max(data.commits_by_year.keys()) + 1,
                )
            )
        else:
            cby_all_years = []
        cby_values = [data.commits_by_year.get(y, 0) for y in cby_all_years]
        f.write(
            self._render_chartjs(
                "chart-commits-by-year",
                "bar",
                cby_all_years,
                [{"label": "Commits", "data": cby_values}],
                y_label="Commits",
            )
        )

        # Commits by timezone
        f.write(html_header(2, "Commits by Timezone"))
        f.write("<table><tr>")
        f.write("<th>Timezone</th><th>Commits</th>")
        f.write("</tr>")
        max_commits_on_tz = max(data.commits_by_timezone.values())
        for i in sorted(list(data.commits_by_timezone.keys()), key=lambda n: int(n)):
            commits = data.commits_by_timezone[i]
            f.write(
                '<tr><th>%s</th><td class="%s">%d</td></tr>'
                % (i, self._heat_td_class(commits, max_commits_on_tz), commits)
            )
        f.write("</table>")

        f.write("</body></html>")
        f.close()

    def create_authors_html(self, data, path):
        ###
        # Authors
        f = open(path + "/authors.html", "w", encoding="utf-8")
        self.print_header(f)

        self.print_nav(f)
        f.write("<h1>Authors</h1>")

        # Authors :: List of authors
        f.write(html_header(2, "List of Authors"))

        f.write('<table class="authors sortable" id="authors">')
        f.write(
            '<tr><th>Author</th><th>Commits (%)</th><th>+ lines</th><th>- lines</th><th>First commit</th><th>Last commit</th><th class="unsortable">Age</th><th>Active days</th><th># by commits</th></tr>'
        )
        for author in data.get_authors(conf["max_authors"]):
            info = data.get_author_info(author)
            f.write(
                "<tr><td>%s</td><td>%d (%.2f%%)</td><td>%d</td><td>%d</td><td>%s</td><td>%s</td><td>%s</td><td>%d</td><td>%d</td></tr>"
                % (
                    author,
                    info["commits"],
                    info["commits_frac"],
                    info["lines_added"],
                    info["lines_removed"],
                    info["date_first"],
                    info["date_last"],
                    info["timedelta"],
                    len(info["active_days"]),
                    info["place_by_commits"],
                )
            )
        f.write("</table>")

        allauthors = data.get_authors()
        if len(allauthors) > conf["max_authors"]:
            rest = allauthors[conf["max_authors"] :]
            f.write(
                '<p class="moreauthors">These didn\'t make it to the top: %s</p>'
                % ", ".join(rest)
            )

        # Build per-author time series data for Chart.js
        self.authors_to_plot = data.get_authors(conf["max_authors"])
        lines_by_authors = {a: 0 for a in self.authors_to_plot}
        commits_by_authors = {a: 0 for a in self.authors_to_plot}

        # time_labels: formatted date strings; per_author_lines/commits: list per author
        time_labels = []
        per_author_lines = {a: [] for a in self.authors_to_plot}
        per_author_commits = {a: [] for a in self.authors_to_plot}

        for stamp in sorted(data.changes_by_date_by_author.keys()):
            time_labels.append(
                datetime.datetime.fromtimestamp(stamp).strftime("%Y-%m-%d")
            )
            for author in self.authors_to_plot:
                if author in data.changes_by_date_by_author[stamp]:
                    lines_by_authors[author] = data.changes_by_date_by_author[stamp][
                        author
                    ]["lines_added"]
                    commits_by_authors[author] = data.changes_by_date_by_author[stamp][
                        author
                    ]["commits"]
                per_author_lines[author].append(lines_by_authors[author])
                per_author_commits[author].append(commits_by_authors[author])

        loc_datasets = [
            {"label": a, "data": per_author_lines[a]} for a in self.authors_to_plot
        ]
        cba_datasets = [
            {"label": a, "data": per_author_commits[a]} for a in self.authors_to_plot
        ]

        f.write(html_header(2, "Cumulated Added Lines of Code per Author"))
        f.write(
            self._render_chartjs(
                "chart-loc-by-author",
                "line",
                time_labels,
                loc_datasets,
                y_label="Lines",
                x_ticks_rotate=True,
            )
        )
        if len(allauthors) > conf["max_authors"]:
            f.write(
                '<p class="moreauthors">Only top %d authors shown</p>'
                % conf["max_authors"]
            )

        f.write(html_header(2, "Commits per Author"))
        f.write(
            self._render_chartjs(
                "chart-commits-by-author",
                "line",
                time_labels,
                cba_datasets,
                y_label="Commits",
                x_ticks_rotate=True,
            )
        )
        if len(allauthors) > conf["max_authors"]:
            f.write(
                '<p class="moreauthors">Only top %d authors shown</p>'
                % conf["max_authors"]
            )

        # Authors :: Author of Month
        f.write(html_header(2, "Author of Month"))
        f.write('<table class="sortable" id="aom">')
        f.write(
            '<tr><th>Month</th><th>Author</th><th>Commits (%%)</th><th class="unsortable">Next top %d</th><th>Number of authors</th></tr>'
            % conf["authors_top"]
        )
        for yymm in reversed(sorted(data.author_of_month.keys())):
            author_dict = data.author_of_month[yymm]
            authors = get_keys_sorted_by_values(author_dict)
            authors.reverse()
            commits = data.author_of_month[yymm][authors[0]]
            authors_str = ", ".join(authors[1 : conf["authors_top"] + 1])
            f.write(
                "<tr><td>%s</td><td>%s</td><td>%d (%.2f%% of %d)</td><td>%s</td><td>%d</td></tr>"
                % (
                    yymm,
                    authors[0],
                    commits,
                    (100.0 * commits) / data.commits_by_month[yymm],
                    data.commits_by_month[yymm],
                    authors_str,
                    len(authors),
                )
            )

        f.write("</table>")

        f.write(html_header(2, "Author of Year"))
        f.write(
            '<table class="sortable" id="aoy"><tr><th>Year</th><th>Author</th><th>Commits (%%)</th><th class="unsortable">Next top %d</th><th>Number of authors</th></tr>'
            % conf["authors_top"]
        )
        for yy in reversed(sorted(data.author_of_year.keys())):
            author_dict = data.author_of_year[yy]
            authors = get_keys_sorted_by_values(author_dict)
            authors.reverse()
            commits = data.author_of_year[yy][authors[0]]
            authors_str = ", ".join(authors[1 : conf["authors_top"] + 1])
            f.write(
                "<tr><td>%s</td><td>%s</td><td>%d (%.2f%% of %d)</td><td>%s</td><td>%d</td></tr>"
                % (
                    yy,
                    authors[0],
                    commits,
                    (100.0 * commits) / data.commits_by_year[yy],
                    data.commits_by_year[yy],
                    authors_str,
                    len(authors),
                )
            )
        f.write("</table>")

        # Domains
        f.write(html_header(2, "Commits by Domains"))
        domains_by_commits = get_keys_sorted_by_value_key(data.domains, "commits")
        domains_by_commits.reverse()  # most first
        f.write('<div class="vtable"><table>')
        f.write("<tr><th>Domains</th><th>Total (%)</th></tr>")
        dom_labels = []
        dom_values = []
        n = 0
        for domain in domains_by_commits:
            if n == conf["max_domains"]:
                break
            n += 1
            info = data.get_domain_info(domain)
            dom_labels.append(domain)
            dom_values.append(info["commits"])
            f.write(
                "<tr><th>%s</th><td>%d (%.2f%%)</td></tr>"
                % (
                    domain,
                    info["commits"],
                    (100.0 * info["commits"] / data.get_total_commits()),
                )
            )
        f.write("</table></div>")
        f.write(
            self._render_chartjs(
                "chart-domains",
                "bar",
                dom_labels,
                [{"label": "Commits", "data": dom_values}],
                y_label="Commits",
                x_ticks_rotate=True,
            )
        )

        f.write("</body></html>")
        f.close()

    def create_files_html(self, data, path):
        ###
        # Files
        f = open(path + "/files.html", "w", encoding="utf-8")
        self.print_header(f)
        self.print_nav(f)
        f.write("<h1>Files</h1>")

        f.write("<dl>\n")
        f.write("<dt>Total files</dt><dd>%d</dd>" % data.get_total_files())
        f.write("<dt>Total lines</dt><dd>%d</dd>" % data.get_total_loc())
        try:
            f.write(
                "<dt>Average file size</dt><dd>%.2f bytes</dd>"
                % (float(data.get_total_size()) / data.get_total_files())
            )
        except ZeroDivisionError:
            pass
        f.write("</dl>\n")

        # Files :: File count by date
        f.write(html_header(2, "File count by date"))

        # use set to get rid of duplicate/unnecessary entries, then sort
        files_by_date = {}
        for stamp in sorted(data.files_by_stamp.keys()):
            date_str = datetime.datetime.fromtimestamp(stamp).strftime("%Y-%m-%d")
            files_by_date[date_str] = data.files_by_stamp[stamp]

        fbd_labels = sorted(files_by_date.keys())
        fbd_values = [files_by_date[d] for d in fbd_labels]
        f.write(
            self._render_chartjs(
                "chart-files-by-date",
                "line",
                fbd_labels,
                [{"label": "Files", "data": fbd_values}],
                y_label="Files",
                x_ticks_rotate=True,
            )
        )

        # f.write('<h2>Average file size by date</h2>')

        # Files :: Extensions
        f.write(html_header(2, "Extensions"))
        f.write(
            "<p><em>Note: Files with excluded extensions are not shown. Configure <code>exclude_exts</code> in gitstats.conf.</em></p>"
        )
        f.write(
            '<table class="sortable" id="ext"><tr><th>Extension</th><th>Files (%)</th><th>Lines (%)</th><th>Lines/file</th></tr>'
        )

        for ext in sorted(data.extensions.keys()):
            files = data.extensions[ext]["files"]
            lines = data.extensions[ext]["lines"]
            try:
                loc_percentage = (100.0 * lines) / data.get_total_loc()
            except ZeroDivisionError:
                loc_percentage = 0
            f.write(
                "<tr><td>%s</td><td>%d (%.2f%%)</td><td>%d (%.2f%%)</td><td>%d</td></tr>"
                % (
                    ext,
                    files,
                    (100.0 * files) / data.get_total_files(),
                    lines,
                    loc_percentage,
                    lines / files,
                )
            )
        f.write("</table>")

        f.write("</body></html>")
        f.close()

    def create_lines_html(self, data, path):
        ###
        # Lines
        f = open(path + "/lines.html", "w", encoding="utf-8")
        self.print_header(f)
        self.print_nav(f)
        f.write("<h1>Lines</h1>")

        f.write("<dl>\n")
        f.write("<dt>Total lines</dt><dd>%d</dd>" % data.get_total_loc())
        f.write("</dl>\n")

        f.write(html_header(2, "Lines of Code"))
        loc_stamps = sorted(data.changes_by_date.keys())
        loc_labels = [
            datetime.datetime.fromtimestamp(s).strftime("%Y-%m-%d") for s in loc_stamps
        ]
        loc_values = [data.changes_by_date[s]["lines"] for s in loc_stamps]
        f.write(
            self._render_chartjs(
                "chart-lines-of-code",
                "line",
                loc_labels,
                [{"label": "Lines", "data": loc_values}],
                y_label="Lines",
                x_ticks_rotate=True,
            )
        )

        f.write("</body></html>")
        f.close()

    def create_tags_html(self, data, path):
        ###
        # tags.html
        f = open(path + "/tags.html", "w", encoding="utf-8")
        self.print_header(f)
        self.print_nav(f)
        f.write("<h1>Tags</h1>")

        f.write("<dl>")
        f.write("<dt>Total tags</dt><dd>%d</dd>" % len(data.tags))
        if len(data.tags) > 0:
            f.write(
                "<dt>Average commits per tag</dt><dd>%.2f</dd>"
                % (1.0 * data.get_total_commits() / len(data.tags))
            )
        f.write("</dl>")

        f.write('<table class="tags">')
        f.write("<tr><th>Name</th><th>Date</th><th>Commits</th><th>Authors</th></tr>")
        # sort the tags by date desc
        tags_sorted_by_date_desc = [
            el[1]
            for el in reversed(
                sorted([(el[1]["date"], el[0]) for el in list(data.tags.items())])
            )
        ]
        for tag in tags_sorted_by_date_desc:
            authorinfo = []
            self.authors_by_commits = get_keys_sorted_by_values(
                data.tags[tag]["authors"]
            )
            for i in reversed(self.authors_by_commits):
                authorinfo.append("%s (%d)" % (i, data.tags[tag]["authors"][i]))
            f.write(
                "<tr><td>%s</td><td>%s</td><td>%d</td><td>%s</td></tr>"
                % (
                    tag,
                    data.tags[tag]["date"],
                    data.tags[tag]["commits"],
                    ", ".join(authorinfo),
                )
            )
        f.write("</table>")

        f.write("</body></html>")
        f.close()

    def create_ai_insights_html(self, data, path):
        """
        Create a dedicated AI Insights page with all AI-generated summaries.
        """
        # Get language from config
        language = conf.get("ai_language", "en")

        f = open(path + "/ai-insights.html", "w", encoding="utf-8")
        self.print_header(f)
        self.print_nav(f)
        f.write(f"<h1>{get_i18n_text('ai_insights_title', language)}</h1>")

        f.write(f"""
        <div class="ai-insights-intro">
            <p>{get_i18n_text("ai_insights_intro", language)}</p>
        </div>
        """)

        # Get all AI summaries
        summaries = data.ai_summaries

        # Define sections with titles and descriptions
        sections = [
            {
                "key": "index",
                "title": get_i18n_text("project_overview", language),
                "description": get_i18n_text("project_overview_desc", language),
            },
            {
                "key": "activity",
                "title": get_i18n_text("activity_patterns", language),
                "description": get_i18n_text("activity_patterns_desc", language),
            },
            {
                "key": "lines",
                "title": get_i18n_text("code_evolution", language),
                "description": get_i18n_text("code_evolution_desc", language),
            },
        ]

        # Generate sections
        for section in sections:
            key = section["key"]
            if key not in summaries:
                continue

            summary_data = summaries[key]
            summary_text = summary_data.get("summary", "")
            error = summary_data.get("error")

            f.write('<div class="ai-insight-section">')
            f.write(f'<h2 id="{key}">{section["title"]}</h2>')
            f.write(
                f'<p class="section-description"><em>{section["description"]}</em></p>'
            )

            if error:
                f.write(f"""
                <div class="ai-summary-error">
                    <p><strong>{get_i18n_text("analysis_unavailable", language)}</strong></p>
                    <p><em>{error}</em></p>
                </div>
                """)
            elif summary_text:
                f.write(f"""
                <div class="ai-summary-content">
                    {summary_text}
                </div>
                """)
            else:
                f.write(f"<p><em>{get_i18n_text('no_analysis', language)}</em></p>")

            f.write("</div>")

        # Add disclaimer
        f.write(f"""
        <div class="ai-disclaimer">
            <h3>{get_i18n_text("about_ai_insights", language)}</h3>
            <p>{get_i18n_text("ai_disclaimer", language)}</p>
            <p>{get_i18n_text("bot_note", language)}</p>
        </div>
        """)

        f.write("</body></html>")
        f.close()

    CHART_COLORS = ["#5b8dee", "#1a7f37", "#cf222e", "#8250df", "#e16f24", "#0550ae"]

    def _render_chartjs(
        self,
        chart_id,
        chart_type,
        labels,
        datasets,
        y_label="Commits",
        x_ticks_rotate=False,
        aspect_ratio=3,
    ):
        """Render a Chart.js chart as inline HTML."""
        is_multi = len(datasets) > 1

        js_datasets = []
        for i, ds in enumerate(datasets):
            color = self.CHART_COLORS[i % len(self.CHART_COLORS)]
            entry = dict(ds)
            if is_multi:
                entry.setdefault("borderColor", color)
                entry.setdefault("backgroundColor", color + "33")
                entry.setdefault("fill", False)
                entry.setdefault("tension", 0.1)
                entry.setdefault("pointRadius", 2)
                entry.setdefault("borderWidth", 1)
            else:
                # single dataset: use CSS var for theme-aware color
                entry["backgroundColor"] = "__CSS_BAR_COLOR__"
                entry["borderColor"] = "__CSS_BAR_COLOR__"
                if chart_type == "line":
                    entry.setdefault("borderWidth", 1)
                    entry.setdefault("pointRadius", 2)
            js_datasets.append(entry)

        labels_json = json.dumps(labels)
        datasets_json = json.dumps(js_datasets)
        # Replace quoted placeholder with JS expression
        datasets_json = datasets_json.replace(
            '"__CSS_BAR_COLOR__"', "getCSSVar('--bar-color')"
        )

        x_ticks_opts = (
            "maxRotation: 45, minRotation: 45" if x_ticks_rotate else "maxRotation: 0"
        )

        legend_display = "true" if is_multi else "false"

        return f"""<div style="max-width:100%;margin-bottom:8px"><canvas id="{chart_id}"></canvas></div>
<script>
(function() {{
  var ctx = document.getElementById('{chart_id}').getContext('2d');
  var chart = new Chart(ctx, {{
    type: '{chart_type}',
    data: {{
      labels: {labels_json},
      datasets: {datasets_json}
    }},
    options: {{
      responsive: true,
      maintainAspectRatio: true,
      aspectRatio: {aspect_ratio},
      plugins: {{
        legend: {{ display: {legend_display} }}
      }},
      scales: {{
        x: {{ ticks: {{ {x_ticks_opts} }} }},
        y: {{ beginAtZero: true, title: {{ display: true, text: '{y_label}' }} }}
      }}
    }}
  }});
  document.addEventListener('themechange', function() {{ chart.update(); }});
}})();
</script>
"""

    def print_header(self, file) -> None:
        """
        Write the HTML document header and opening body tag into the provided writable file.

        This writes the DOCTYPE, head section (title from self.title), a link to the configured stylesheet, a generator meta tag, an inclusion of sortable.js, an embedded client-side theme toggle script (init, toggle, and icon update handlers using localStorage), and the opening <body> tag.

        Parameters:
                file: A writable file-like object opened for text output where the HTML header will be written.
        """
        file.write(
            """<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>GitStats - %s</title>
	<!-- Apply theme before CSS loads to prevent flash of unstyled content -->
	<script>(function(){var t=localStorage.getItem('theme')||'light';document.documentElement.setAttribute('data-theme',t);})();</script>
	<link rel="stylesheet" href="%s" type="text/css">
	<meta name="generator" content="GitStats %s">
	<script type="text/javascript" src="sortable.js"></script>
	<script type="text/javascript" src="chart.umd.min.js"></script>
	<script>
		function getCSSVar(v) { return getComputedStyle(document.documentElement).getPropertyValue(v).trim(); }

		function toggleTheme() {
			const currentTheme = document.documentElement.getAttribute('data-theme');
			const newTheme = currentTheme === 'dark' ? 'light' : 'dark';
			document.documentElement.setAttribute('data-theme', newTheme);
			localStorage.setItem('theme', newTheme);
			updateThemeIcon(newTheme);
		}

		function updateThemeIcon(theme) {
			const button = document.getElementById('theme-toggle');
			if (button) {
				button.innerHTML = theme === 'dark' ? '☀️' : '🌙';
				button.setAttribute('aria-label', theme === 'dark' ? 'Switch to light mode' : 'Switch to dark mode');
			}
		}

		document.addEventListener('DOMContentLoaded', function() {
			updateThemeIcon(document.documentElement.getAttribute('data-theme'));
		});
	</script>
</head>
<body>
"""
            % (self.title, conf["style"], get_version)
        )

    def print_nav(self, file) -> None:
        """
        Write the navigation bar HTML (page links and a client-side theme-toggle button) to the given writable file-like object.

        Parameters:
            file: A writable file-like object opened in text mode where the navigation HTML will be written.
        """
        # Check if AI insights are available
        has_ai = hasattr(self.data, "ai_summaries") and self.data.ai_summaries

        ai_link = (
            '<li><a href="ai-insights.html">AI Insights</a></li>' if has_ai else ""
        )

        github_icon = (
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="20" height="20" '
            'fill="currentColor" aria-hidden="true">'
            '<path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 '
            "0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15"
            "-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07"
            "-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 "
            ".67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82"
            ".44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25"
            ".54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8"
            'c0-4.42-3.58-8-8-8z"/></svg>'
        )

        file.write(
            f"""
            <div class="nav">
            <a href="index.html" class="nav-brand">GitStats</a>
            <ul>
            <li><a href="index.html">General</a></li>
            <li><a href="activity.html">Activity</a></li>
            <li><a href="authors.html">Authors</a></li>
            <li><a href="files.html">Files</a></li>
            <li><a href="lines.html">Lines</a></li>
            <li><a href="tags.html">Tags</a></li>
            {ai_link}
            </ul>
            <div class="nav-right">
            <a href="https://github.com/shenxianpeng/gitstats" class="nav-github" target="_blank" rel="noopener" aria-label="GitHub">{github_icon}</a>
            <button id="theme-toggle" class="theme-toggle" onclick="toggleTheme()" aria-label="Switch to dark mode">🌙</button>
            </div>
            </div>
            """
        )

    def get_ai_summary_html(self, page_type):
        """
        Generate HTML for AI-powered summary section.

        Args:
            page_type: The type of page (index, activity, authors, lines)

        Returns:
            HTML string for the AI summary section
        """
        if not hasattr(self.data, "ai_summaries") or not self.data.ai_summaries:
            return ""

        summary_data = self.data.ai_summaries.get(page_type, {})
        summary_text = summary_data.get("summary", "")
        error = summary_data.get("error")

        if error:
            # Show error message with graceful degradation
            return f"""
            <div class="ai-summary ai-summary-error">
                <h3>AI Insights</h3>
                <p><em>AI analysis is currently unavailable: {error}</em></p>
            </div>
            """

        if not summary_text:
            return ""

        return f"""
        <div class="ai-summary">
            <h3>AI-Powered Insights</h3>
            <div class="ai-summary-content">
                {summary_text}
            </div>
        </div>
        """


def html_header(level, text):
    name = html_linkify(text)
    return '\n<h%d id="%s"><a href="#%s">%s</a></h%d>\n\n' % (
        level,
        name,
        name,
        text,
        level,
    )


def html_linkify(text):
    return text.lower().replace(" ", "_")


def get_keys_sorted_by_values(dict):
    return [el[1] for el in sorted([(el[1], el[0]) for el in list(dict.items())])]


# dict['author'] = { 'commits': 512 } - ...key(dict, 'commits')
def get_keys_sorted_by_value_key(d, key):
    return [el[1] for el in sorted([(d[el][key], el) for el in list(d.keys())])]
