#!/usr/bin/env python3
"""Clone famous repos, run gitstats, and generate a gallery index page.

This is a standalone script used by CI (not part of the gitstats package).
Output goes to ./gallery/ which gets deployed to GitHub Pages.
"""

import json
import os
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

REPOS = [
    ("Linux Kernel",   "torvalds/linux",          15000),
    ("CPython",        "python/cpython",          10000),
    ("VS Code",        "microsoft/vscode",        10000),
    ("Git",            "git/git",                  8000),
    ("nginx",          "nginx/nginx",              8000),
    ("Kubernetes",     "kubernetes/kubernetes",   10000),
]

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
OUT = ROOT / "gallery"


def run(cmd, **kw):
    subprocess.run(cmd, capture_output=True, text=True, check=True, **kw)


def generate_index(repos_meta):
    """Write gallery/index.html."""
    rows = ""
    for name, repo, depth, summary in repos_meta:
        st = summary or {}
        c = st.get("total_commits", 0)
        a = st.get("total_authors", 0)
        f = st.get("total_files", 0)
        l = st.get("total_lines", 0)
        repo_id = repo.split("/")[1]
        rows += f"""
        <tr>
          <td><a href="repos/{repo_id}/index.html"><strong>{name}</strong></a></td>
          <td><a href="https://github.com/{repo}">{repo}</a></td>
          <td style="text-align:right">{c:,}</td>
          <td style="text-align:right">{a:,}</td>
          <td style="text-align:right">{f:,}</td>
          <td style="text-align:right">{l:,}</td>
        </tr>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>GitStats Gallery — Famous Open-Source Projects</title>
<meta name="description" content="Git statistics reports for Linux Kernel, CPython, VS Code, Git, nginx, Kubernetes — generated by GitStats.">
<meta name="keywords" content="gitstats, git statistics, linux kernel git statistics, github repository stats">
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 960px; margin: 0 auto; padding: 20px; background: #0d1117; color: #e6edf3; }}
  h1 {{ font-size: 2rem; border-bottom: 1px solid #30363d; padding-bottom: 12px; }}
  table {{ border-collapse: collapse; width: 100%; }}
  th, td {{ padding: 10px 12px; text-align: left; border-bottom: 1px solid #21262d; }}
  th {{ background: #161b22; font-weight: 600; }}
  tr:hover {{ background: #1c2333; }}
  a {{ color: #58a6ff; text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  .meta {{ color: #8b949e; font-size: 0.9rem; margin-top: 20px; }}
</style>
</head>
<body>
<h1>⚡ GitStats Gallery</h1>
<p>Live Git statistics for well-known open-source projects. Click a project name to view its full report.</p>
<table>
<thead><tr><th>Project</th><th>Repository</th><th>Commits</th><th>Authors</th><th>Files</th><th>LOC</th></tr></thead>
<tbody>{rows}</tbody>
</table>
<p class="meta">Generated by <a href="https://github.com/shenxianpeng/gitstats">GitStats</a> &middot; {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}</p>
</body>
</html>"""
    (OUT / "index.html").write_text(html)
    print(f"  Gallery index → {OUT / 'index.html'}")


def main():
    print("=" * 50)
    print("  GitStats Gallery Generator")
    print("=" * 50)

    OUT.mkdir(parents=True, exist_ok=True)
    repos_meta = []

    with tempfile.TemporaryDirectory(prefix="gallery-") as tmp:
        work = Path(tmp)
        for name, repo, depth in REPOS:
            repo_id = repo.split("/")[1]
            clone_dir = work / repo_id
            report_dir = OUT / "repos" / repo_id
            print(f"\n  [{repo_id}] {name} (depth={depth})")

            if report_dir.exists():
                shutil.rmtree(report_dir)

            # Clone
            print("    Cloning…")
            run(["git", "clone", "--depth", str(depth),
                 f"https://github.com/{repo}.git", str(clone_dir)], timeout=900)

            # Run gitstats
            print("    Running gitstats…")
            report_dir.mkdir(parents=True, exist_ok=True)
            run([sys.executable, "-m", "gitstats", str(clone_dir), str(report_dir), "-f", "json"],
                cwd=ROOT, timeout=600)

            # Parse JSON summary (gitstats writes {outputpath}.json one level up)
            json_path = Path(f"{report_dir}.json")
            summary = {}
            if json_path.exists():
                with open(json_path) as f:
                    data = json.load(f)
                c = data.get("cache", {})
                for k in ("total_commits", "total_authors", "total_files", "total_lines"):
                    summary[k] = c.get(k, 0)

            repos_meta.append((name, repo, depth, summary))
            shutil.rmtree(clone_dir, ignore_errors=True)

    generate_index(repos_meta)
    print(f"\n  Done! {len(repos_meta)} reports in {OUT}/")


if __name__ == "__main__":
    main()
